修改monitor后的版本

diff --git a/aging_test/tools-test-aging b/aging_test/tools-test-aging
--- a/aging_test/tools-test-aging
+++ b/aging_test/tools-test-aging
@@ -2,7 +2,7 @@
 
 version()
 {
-	echo "$prog_name - v1.3 - 20130927 13:34"
+	echo "$PROG_NAME - v1.3 - 20130927 13:34"
 }
 
 usage()
@@ -10,51 +10,61 @@ usage()
 	echo ""
 	version
 	echo "usage:"
-	echo "    $prog_name [--io disk|raid|none [--part <path>]]"
+	echo "    $PROG_NAME [--io disk|raid|none [--part <path>]]"
 	echo "        [--net none|both|transmit|receive --role a|b [--eth0-remote-ip <ip>]]"
 	echo "        [--cpu full|none]"
-	echo "           如果要测试网络请先确认网络连接. '设备a' 和 '设备b' 网卡(第一个网卡除外)按顺序一对一直连, 例如: '设备a' 的 'LAN1' 和 '设备b' 的 'LAN2' 连接"
+	echo "           如果要测试网络请先确认网络连接. '设备a' 和 '设备b' 网卡(第一个网卡除外)按顺序一对一直连,"
+	echo "           例如: '设备a' 的 'LAN1' 和 '设备b' 的 'LAN1' 连接"
 	echo "           测试启动后会一直运行, 重启后也会自动运行"
 	echo "           测试模块可选, 默认使用该模块第一个可选参数启动测试"
 	echo "           网络模块默认不启动, 启动网络模块时, 必须输入 --role 选项设定本机角色(a/b), 另一端的设备设定相对的角色(b/a)"
 	echo "           io  测试模块参数 disk: 硬盘; raid: 卷组. 自动扫描所有硬盘(系统盘除外)或卷组测试."
 	echo "               如果需要测试系统盘, 在系统盘上新建空闲分区, 输入'--part path'测试, path为分区完整路径, 如/dev/sda2"
+	echo "               在测试期间如果磁盘、分区、或者raid发生异常， 在每小时的0，15，30，45分钟时会对相应的io设备进行累计错误计数 "	
+        echo "	             在测试io期间不要插入新磁盘，磁盘拔掉之后请重新插入到原来的插槽"
 	echo "           net 测试模块参数 both: 双向链路; transmit: 发送链路; receive: 接收链路. 自动按指定的角色(a/b)设置网卡(第一个网卡除外)ip地址测试"
 	echo "               如果需要测试第一个网卡eth0, 需要输入'--eth0-remote-ip ip'指定对端的ip地址"
-	echo "           cpu 测试模块参数 full: 全速运行"
-	echo "           参数 'none' 表示不启动该测试模块"
+	echo "               在测试期间如果网络发生异常,在每小时的0,15,30,45分钟会对相应的网络设备进行累计错误计数"
+	echo "               如果net的参数为receive不进行累计错误的计数"
+	echo "           cpu 测试模块参数full: 全速运行"
+	echo "               参数 'none' 表示不启动该测试模块"
 	echo ""
-	echo "       $prog_name --stop"
-	echo "           中止当前测试, 系统重启后会自动启动测试"
+	echo "       $PROG_NAME --stop"
+	echo "           结束测试,显示累计错误,系统重启后不再自动启动测试"
 	echo ""
-	echo "       $prog_name --remove"
-	echo "           停止测试, 系统重启后不再自动启动测试"
+	echo "       $PROG_NAME --status"
+	echo "           查看测试程序启动时间、启动的参数、相关模块累计的错误信息"
 	echo ""
-	echo "       $prog_name --status"
-	echo "           查看测试程序运行状态"
-	echo ""
-	echo "       $prog_name --help"
-	echo ""
-	echo "       $prog_name --version"
+	echo "       $PROG_NAME --help"
+	echo "            显示此帮助文档"
+	echo ""	
+	echo "       $PROG_NAME --version"
+	echo "            显示版本信息"
 }
 
 check_arg_io()
 {
-	if [ "$io" != "disk" -a "$io" != "raid" -a "$io" != "none" ]; then
+	local sys_part
+	if [ "$IO" != "disk" -a "$IO" != "raid" -a "$IO" != "none" ]; then
 		echo "--io 参数错误"
 		return 1
 	fi
-	
-	if [ "x$part" != "x" ]; then
-		if mount -l | grep " / " | grep -q "$part"; then
-			echo "$part为系统分区, 不能做io测试"
+	sys_part=`mount -l |grep " / " | cut -d ' ' -f 1`
+	if [ -L $sys_part ];then
+		sys_part=`ls -l $sys_part | awk '{print $NF}'`
+	fi
+	sys_part=`basename $sys_part`
+	SYS_DISK=`echo $sys_part|tr -d [:digit:]`
+	if [ "x$PART" != "x" ]; then
+		if [ $sys_part = `basename $PART` ]; then
+			echo "$PART为系统分区，不能做io测试"
 			return 1
 		fi
-		
-		if [ ! -b $part ] || ls /sys/block | grep -q `basename $part`; then
-			echo "$part不是分区"
+		if [ ! -b $PART ] || ls /sys/block | grep -q `basename $PART`; then
+			echo "$PART不是分区"
 			return 1
 		fi
+
 	fi
 
 	return 0
@@ -62,17 +72,17 @@ check_arg_io()
 
 check_arg_net()
 {
-	if [ "$net" != "both" -a "$net" != "transmit" -a "$net" != "receive" -a "$net" != "none" ]; then
+	if [ "$NET" != "both" -a "$NET" != "transmit" -a "$NET" != "receive" -a "$NET" != "none" ]; then
 		echo "--net 参数错误"
 		return 1
-	elif [ "$net" != "none" -a "$role" != "a" -a "$role" != "b" ]; then
+	elif [ "$NET" != "none" -a "$ROLE" != "a" -a "$ROLE" != "b" ]; then
 		echo "--role 参数错误"
 		return 1
 	fi
 
-	if [ "x$eth0_remote_ip" != "x" ]; then
-		if ! ping -c 4 $eth0_remote_ip >/dev/null; then
-			echo "ip地址 $eth0_remote_ip 不通, 请检查ip地址是否正确, 或网络连接是否正常"
+	if [ "x$ETH0_REMOTE_IP" != "x" ]; then
+		if ! ping -c 4 $ETH0_REMOTE_IP >/dev/null; then
+			echo "ip地址 $ETH0_REMOTE_IP 不通, 请检查ip地址是否正确, 或网络连接是否正常"
 			return 1
 		fi
 	fi
@@ -81,7 +91,7 @@ check_arg_net()
 
 check_arg_cpu()
 {
-	if [ "$cpu" != "full" -a "$cpu" != "none" ]; then
+	if [ "$CPU" != "full" -a "$CPU" != "none" ]; then
 		echo "--cpu 参数错误"
 		return 1
 	else
@@ -93,36 +103,39 @@ test_io()
 {
 	local file
 	local prefix
-	local sys_disk
-	
-	sys_disk=`mount -l | grep " / " | cut -d ' ' -f 1`
-	if [ -L $sys_disk ]; then
-		sys_disk=`ls -l $sys_disk | awk '{ print $NF }'`
-	fi
-	sys_disk=`basename $sys_disk | tr -d [:digit:]`
+	local disks
+	local disk
 
-	if [ "$io" = "disk" ]; then
+	if [ "$IO" = "disk" ]; then
 		prefix="sd"
 	else
 		prefix="md"
 	fi
-	disks=`ls /sys/block | grep $prefix | grep -v "$sys_disk"`
-	if [ "x$part" != "x" ]; then
-		disks="$disks `basename $part`"
+	disks=`ls /sys/block | grep $prefix | grep -v "$SYS_DISK"`
+	if [ "x$PART" != "x" ]; then
+		disks="${disks} `basename $PART`"
 	fi
 	for disk in $disks
 	do
-		file=/tmp/.${prog_name}_io_$disk
+		file=/tmp/.${PROG_NAME}_io_$disk
 		cat << EOF >$file
 #!/bin/sh
 while true
 do
-	dd if=/dev/zero of=/dev/$disk bs=1M >/dev/null 2>&1
-	dd if=/dev/$disk of=/dev/null bs=1M >/dev/null 2>&1
+	if [ ! -b /dev/$disk ]; then
+		return 1
+	fi						                
+	dd if=/dev/zero of=/dev/$disk bs=1M oflag=direct >/dev/null 2>&1
+	dd if=/dev/$disk of=/dev/null bs=1M iflag=direct >/dev/null 2>&1
+	sleep 1   
+	##防止因为dd 发送数据到内核 引起的iostat显示数据过高
 done
 EOF
 		chmod +x $file
 		$file &
+		if [ $REBOOTTIMES -eq 0 ];then
+			echo "io_${disk}_errors=0" >> $ERROR_STATUS_FILE
+		fi
 	done
 }
 
@@ -135,66 +148,72 @@ test_net()
 	local file
 	local host_addr_local
 	local host_addr_remote
-	
+
 	eths=`ls /sys/class/net | grep "eth[1-9]"`
-	
-	if [ "$role" = "a" ]; then
+
+	if [ "$ROLE" = "a" ]; then
 		host_addr_local=1
 		host_addr_remote=2
 	else
 		host_addr_local=2
 		host_addr_remote=1
 	fi
-	
-	if [ "$net" != "transmit" ]; then
-		file="/tmp/.${prog_name}_net_receive"
+
+	if [ "$NET" != "transmit" ]; then
+		file="/tmp/.${PROG_NAME}_net_receive"
 		echo "#!/bin/sh" >$file
 		for eth in $eths
 		do
 			i=`echo $eth | tr -d "eth"`
 			echo "ifconfig $eth 192.168.$i.$host_addr_local" >>$file
 		done
-		
+
 		echo "iperf -s -l 100000 >/dev/null 2>&1" >>$file
 		chmod +x $file
 		$file &
 	fi
 
-	if [ "$net" = "receive" ]; then
+	if [ "$NET" = "receive" ]; then
 		return
 	fi
-	
+
 	for eth in $eths
 	do
 		i=`echo $eth | tr -d "eth"`
-		file="/tmp/.${prog_name}_net_transmit_$eth"
+		file="/tmp/.${PROG_NAME}_net_transmit_$eth"
 		cat << EOF >$file
 #!/bin/sh
 ifconfig $eth 192.168.$i.$host_addr_local
 
 while true
-do
-	iperf -c 192.168.$i.$host_addr_remote -l 100000 -t 3600 >/dev/null 2>&1
-	sleep 5
-done
+	do
+		iperf -c 192.168.$i.$host_addr_remote -l 100000 -t 3600 >/dev/null 2>&1
+		sleep 5
+	done
 EOF
 		chmod +x $file
 		$file &
+		if [ $REBOOTTIMES -eq 0 ];then
+			echo "net_${eth}_errors=0" >>$ERROR_STATUS_FILE
+		fi
 	done
-	
+
 	# 单独处理eth0的发包测试
-	file="/tmp/.${prog_name}_net_transmit_eth0"
-			cat << EOF >$file
+	file="/tmp/.${PROG_NAME}_net_transmit_eth0"
+	cat << EOF >$file
 #!/bin/sh
 
 while true
 do
-	iperf -c $eth0_remote_ip -l 100000 -t 3600 >/dev/null 2>&1
+	iperf -c $ETH0_REMOTE_IP -l 100000 -t 3600 >/dev/null 2>&1
 	sleep 5
 done
 EOF
-		chmod +x $file
-		$file &
+	chmod +x $file
+	$file &
+	if [ $REBOOTTIMES -eq 0 ];then
+		echo "net_eth0_errors=0" >> $ERROR_STATUS_FILE
+	fi
 }
 
 test_cpu()
@@ -205,10 +224,10 @@ test_cpu()
 	cpuids=`cat /proc/cpuinfo | grep processor | awk '{ print $3 }'`
 	for cpuid in $cpuids
 	do
-		file=/tmp/.${prog_name}_cpu_$cpuid
+		file=/tmp/.${PROG_NAME}_cpu_$cpuid
 		cat << EOF >$file
 #!/bin/sh
-yes >/dev/null
+	yes >/dev/null
 EOF
 		chmod +x $file
 		$file &
@@ -221,65 +240,125 @@ stop()
 	local files
 	local pid
 	local op=$1
+	local count=10
 
-	rm -f $status_file
-	
-	pid=`ps -ef | grep "${prog_name} --monitor" | grep -v "grep" | awk '{ print $2 }'`
-	if [ ! -z "$pid" ]; then
-		kill -9 $pid
-	fi
+	while true
+	do
+		pid=`ps -ef | grep "${PROG_NAME} --monitor" | grep -v "grep" | awk '{ print $2 }'`
+		if [ ! -z "$pid" ];then
+			if [ count -ge 0 ];then
+				sleep 1
+				count=$((count-1))
+			else
+				kill -9 $pid
+			fi
+		else
+			break
+		fi
+		
+	done
 
 	cd /tmp
-	files=`ls .${prog_name}_* 2>/dev/null`
-	rm -f .${prog_name}_*
+	files=`ls .${PROG_NAME}_* 2>/dev/null`
+	rm -f .${PROG_NAME}_*
 	for file in $files
 	do
 		killall $file >/dev/null 2>&1
 	done
-	
+
 	killall dd >/dev/null 2>&1
 	killall iperf >/dev/null 2>&1
 	killall iperf >/dev/null 2>&1
 	killall yes >/dev/null 2>&1
-	
-	if [ "$op" = "forever" ]; then
-		logger -t [$prog_name] "停止测试"
+
+	sed -i /"$PROG_NAME"/d /etc/rc.local
+	sed -i /"$PROG_NAME"/d /etc/crontab
+	logger -t [$PROG_NAME] "结束测试"
+
+	if [ -f "$ERROR_STATUS_FILE" ];then
+		echo ""
+		cat $ERROR_STATUS_FILE | sed 's/=/\t/g'
+		sed -i 's/running/stop/g' $ERROR_STATUS_FILE >/dev/null 2>&1
+		echo ""
+		rm -I /tmp/.aging-test-status > /dev/null 2>&1
+		mv $ERROR_STATUS_FILE $ERROR_STATUS_FILE`date "+%Y%m%d%H%M%S"` >/dev/null 2>&1
 	else
-		logger -t [$prog_name] "中止测试"
+		echo "$PROG_NAME 没有运行！"
 	fi
+
+	rm -f $RUN_STATUS_FILE
 }
 
-remove()
-{
-	stop "forever"
-	sed -i /"$prog_name"/d /etc/rc.local
-	sed -i /"$prog_name"/d /etc/crontab
-}
 
 monitor()
 {
 	local files
 	local file
 	local procs
+	local tmpfile=/tmp/.aging-test-status
+	local disk
+	local prog_nam
+	prog_nam=`basename $0`
 	
-	cd /tmp
-	procs=`ps -ef | grep ".${prog_name}_"`
-	files=`ls .${prog_name}_*`
+	##io错误
+	#eval "cat $ERROR_STATUS_FILE"   
+	diskcount=`iostat|wc -l`
+	iostat -m 2 2 |sed "1,$diskcount"d |sed "1,/Device/"d| awk '{print $1"  "$3"  "$4}' > $tmpfile
+	name_io=`cat $ERROR_STATUS_FILE| sed -n '/io/'p | awk -F _ '{print $2}'`
+	for disk in $name_io 
+	do	
+		orgdisk=$disk
+		if [ ! -z `echo $disk | sed -n '/sd/'p` ];then
+			disk=`echo $disk|tr -d [:digit:]`
+		fi
+		monitor_io_errors=`cat $ERROR_STATUS_FILE |grep $disk | awk -F = '{print $2}'|awk '{print $1}'`
+		tmpvar=`cat ${tmpfile} |grep $disk`	
+		if [ -z "$tmpvar" ];  then
+			sed -i "s/${disk}.*/${orgdisk}_errors=$((monitor_io_errors+1)) 未检测到硬盘/" $ERROR_STATUS_FILE
+			logger -t [$prog_nam] "$disk 发生io错误 未检测到硬盘"
+		elif [ ! -z `echo $tmpvar | awk '{if ($2<=10&&$3<=10) print $1}'` ];then
+			sed -i "s/${disk}.*/${orgdisk}_errors=$((monitor_io_errors+1))/" $ERROR_STATUS_FILE
+			logger -t [$prog_nam] "$disk 发生io错误"
+		else
+			sed -i "s/${disk}.*/${orgdisk}_errors=${monitor_io_errors}/" $ERROR_STATUS_FILE
+		fi
+	done
+	##网络错误
+	sar -n DEV 1 3 | sed -n '/Average/'p | sed -e '0,/IFACE/'d -e '/lo/'d | awk \
+		'{if($6<=10) {print $2"  "$6}}' >> ${tmpfile}
+	name=`cat $ERROR_STATUS_FILE | sed -n '/net/'p | awk -F _ '{print $2}'`
+	for monitoreth in $name;
+	do
+		monitor_errors=`cat $ERROR_STATUS_FILE | sed -n "/$monitoreth/p" | awk -F = '{print $2}'`
+		tmpvar=`cat ${tmpfile} |sed -n "/$monitoreth/"p`
+
+		if [ ! -z "$tmpvar" ]; then
+			sed -i "s/${monitoreth}_errors=.*/${monitoreth}_errors=$((monitor_errors+1))/" $ERROR_STATUS_FILE
+			logger -t [$prog_nam] "$monitoreth 发生网络错误"
+		fi
+	done
+	
+	#重新启动停掉的进程
+	procs=`ps -ef | grep ".${prog_nam}_"`
+	files=`ls /tmp/.${prog_nam}_*`
 	for file in $files
 	do
 		if ! echo $procs | grep -q $file; then
 			$file &
 		fi
 	done
+
+
 }
 
 status()
 {
-	if [ -f $status_file ]; then
-		echo "$prog_name 正在运行"
-		cat $status_file
+	if [ -f $RUN_STATUS_FILE ]; then
+		echo "$PROG_NAME 正在运行"
+		cat $RUN_STATUS_FILE
+		cat $ERROR_STATUS_FILE
 	else
-		echo "$prog_name 没有运行"
+		echo "$PROG_NAME 没有运行"
 	fi
 }
 
@@ -289,33 +368,31 @@ check_param()
 	local param=$2
 	if [ "x$param" = "x" ] || echo $param | grep -q "^--"; then
 		echo "选项 $op 参数为空"
-		param_error=1
+		PARAM_ERROR=1
 	fi
 }
 
 ################################# 主程序开始 ###################################
-prog_name=`basename $0`
+PROG_NAME=`basename $0`
 if echo $0 | grep -q "^/"; then
-	cmdline="$0 $@"
+	CMDLINE="$0 $@"
 else
-	cmdline="$PWD/$0 $@"
+	CMDLINE="$PWD/$0 $@"
 fi
-status_file="/tmp/.status_$prog_name"
-
-param_error=0
-role=""
-io="disk"
-net="none"
+RUN_STATUS_FILE="/tmp/.status_$PROG_NAME"
+PARAM_ERROR=0
+ROLE=""
+IO="disk"
+NET="none"
 cpu="full"
-eth0_remote_ip=""
-part=""
-
+ETH0_REMOTE_IP=""
+PART=""
+SYS_DISK=""
+ERROR_STATUS_FILE="/var/log/aging-test-status"
+REBOOTTIMES=0
 if [ ! -z "$1" ]; then
 	if [ "$1" = "--stop" ]; then
 		stop
-		exit 0
-	elif [ "$1" = "--remove" ]; then
-		remove
 		exit 0
 	elif [ "$1" = "--monitor" ]; then
 		monitor
@@ -332,36 +409,36 @@ if [ ! -z "$1" ]; then
 	fi
 fi
 
-while [ ! -z "$1" -a $param_error -ne 1 ]
+while [ ! -z "$1" -a $PARAM_ERROR -ne 1 ]
 do
 	case "$1" in
 		--role)
-		role=$2
+		ROLE=$2
 		check_param $1 $2
 		shift
 		;;
 		--io)
-		io=$2
+		IO=$2
 		check_param $1 $2
 		shift
 		;;
 		--net)
-		net=$2
+		NET=$2
 		check_param $1 $2
 		shift
 		;;
 		--cpu)
-		cpu=$2
+		CPU=$2
 		check_param $1 $2
 		shift
 		;;
 		--eth0-remote-ip)
-		eth0_remote_ip=$2
+		ETH0_REMOTE_IP=$2
 		check_param $1 $2
 		shift
 		;;
 		--part)
-		part=$2
+		PART=$2
 		check_param $1 $2
 		shift
 		;;
@@ -373,8 +450,7 @@ do
 	esac
 	shift
 done
-
-if [ $param_error -ne 0 ]; then
+if [ $PARAM_ERROR -ne 0 ]; then
 	usage
 	exit 1
 fi
@@ -386,34 +462,50 @@ if [ $check_ok -ne 1 ]; then
 	exit 1
 fi
 
-if [ "$io" = "none" ] && [ "$net" = "none" ] && [ "$cpu" = "none" ]; then
+if [ "$IO" = "none" ] && [ "$NET" = "none" ] && [ "$CPU" = "none" ]; then
 	echo "没有指定测试模块, 程序退出"
 	exit 0
 fi
 
-if [ -f $status_file ]; then
-	echo "$prog_name 已经运行"
-	cat $status_file
-	echo "请先停止之前的测试, 再启动新的测试"
+if [ -f $RUN_STATUS_FILE ]; then
+	echo "$PROG_NAME 已经运行"
+	cat $RUN_STATUS_FILE
+	echo "请先结束之前的测试, 再启动新的测试"
 	exit 0
 fi
 
-cat << EOF >$status_file
+cat << EOF >$RUN_STATUS_FILE
 启动时间: `date "+%Y/%m/%d %H:%M:%S"`
-运行参数: io=$io, part=$part; net=$net, role=$role, eth0_remote_ip=$eth0_remote_ip; cpu=$cpu
+运行参数: io=$IO, part=$PART; net=$NET, role=$ROLE, eth0_remote_ip=$ETH0_REMOTE_IP; cpu=$CPU
 EOF
 
-logger -t [$prog_name] "开始测试"
-cat $status_file | logger -t [$prog_name]
-
-if ! grep -q "$prog_name" /etc/rc.local; then
-	echo "$cmdline &" >>/etc/rc.local
-	echo "0,15,30,45 * * * * $PWD/$prog_name --monitor" >>/etc/crontab
+#判断异常重启次数
+if [ -f "$ERROR_STATUS_FILE" ]; then
+	n=`cat $ERROR_STATUS_FILE|sed -n '/abnormal_reboot/'p|awk -F = '{print $2}'`
+	sed -i "s/abnormal_reboot=.*/abnormal_reboot=$((n+1))/" $ERROR_STATUS_FILE
+	REBOOTTIMES=1
+else
+	cat << EOF >$ERROR_STATUS_FILE
+run_status=running
+abnormal_reboot=0
+EOF
 fi
 
-[ "$io" != "none" ] && test_io&
-[ "$net" != "none" ] && test_net&
-[ "$cpu" != "none" ] && test_cpu&
+logger -t [$PROG_NAME] "开始测试"
+cat $RUN_STATUS_FILE | logger -t [$PROG_NAME]
 
-echo "$prog_name 开始测试"
-cat $status_file
+if ! grep -q "$PROG_NAME" /etc/rc.local; then
+	echo "$CMDLINE &" >>/etc/rc.local
+	echo "0,15,30,45 * * * * root $PWD/$PROG_NAME --monitor" >>/etc/crontab
+	chmod +x /etc/rc.local
+fi
+
+
+[ "$IO" != "none" ] && test_io&
+[ "$NET" != "none" ] && test_net&
+[ "$CPU" != "none" ] && test_cpu&
+
+echo "$PROG_NAME 开始测试"
+cat $RUN_STATUS_FILE
+sleep 2
+cat $ERROR_STATUS_FILE
